server:
  compression:
    enabled: true
    min-response-size: 1KB
  servlet:
    context-path:
spring:
  profiles:
    active: '@profile.active@'
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  thymeleaf:
    cache: false
    prefix: classpath:templates/

custom:
  features-enable:
    wechat: false
    kindle: false