server:
  compression:
    enabled: true
    min-response-size: 1KB
  servlet:
    context-path:
spring:
  application:
    name: online-tools
  profiles:
    active: @profile.active@
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  thymeleaf:
    cache: false
    prefix: classpath:templates/
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
logging:
  config: classpath:config/logback-spring.xml

custom:
  features-enable:
    wechat: false
    kindle: false
