### login
GET {{url}}/pcr/login?code=041garFa1Qpisz0klpGa10C7O43garFa

###
GET {{url}}/pcr/princess

### activity list
GET {{url}}/pcr/activity

### current activity
GET {{url}}/pcr/activity/current

### boss list
GET {{url}}/pcr/boss?activityId=3

### axis list
GET {{url}}/pcr/axis?activityId=&bossId=&princessList=[2]&invertSelection=true

### add axis
PUT {{url}}/pcr/axis
Content-Type: application/json

{
  "bossId": 123,
  "damageAmount": "",
  "imgPath": "",
  "princessList": "[{\"id\":4,\"star\":5}]"
}

### uplaod
POST {{url}}/pcr/upload?file=123
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="Snipaste_2019-12-09_15-44-35.png"

< /Files/yj/Snipaste_2019-12-09_15-44-35.png
--WebAppBoundary--
